'use client';

import { useState } from 'react';
import { Share2, Copy, Check, Download } from 'lucide-react';

interface ShareCardProps {
  symbol: string;
  direction: string;
  confidence: number;
  technicalScore: number;
  fundamentalScore: number;
  sentimentScore: number;
  price: number;
  targetPrice?: number;
  summary: string;
}

export default function ShareCard({
  symbol, direction, confidence, technicalScore, fundamentalScore,
  sentimentScore, price, targetPrice, summary,
}: ShareCardProps) {
  const [copied, setCopied] = useState(false);
  const [showCard, setShowCard] = useState(false);

  const dirLabel: Record<string, string> = {
    bullish: 'Bullish Signals', bearish: 'Bearish Signals', neutral: 'Mixed Signals',
    BUY: 'Bullish Signals', SELL: 'Bearish Signals', HOLD: 'Mixed Signals',
  };
  const dirEmoji: Record<string, string> = {
    bullish: '📈', bearish: '📉', neutral: '➡️',
    BUY: '📈', SELL: '📉', HOLD: '➡️',
  };

  const label = dirLabel[direction] || 'Mixed Signals';
  const emoji = dirEmoji[direction] || '➡️';
  const upside = targetPrice && price > 0 ? ((targetPrice - price) / price * 100).toFixed(1) : null;

  const generateText = () => {
    const lines = [
      `${emoji} ${symbol} Analysis Summary`,
      ``,
      `Direction: ${label}`,
      `Confidence: ${(confidence * 100).toFixed(0)}%`,
      `Price: $${price.toFixed(2)}${targetPrice ? ` | Fair Value: $${targetPrice.toFixed(2)}` : ''}`,
      upside ? `Estimated Upside: ${upside}%` : '',
      ``,
      `Scores:`,
      `  Technical: ${technicalScore}/100`,
      `  Fundamental: ${fundamentalScore}/100`,
      `  Sentiment: ${sentimentScore}/100`,
      ``,
      summary.length > 200 ? summary.slice(0, 200) + '...' : summary,
      ``,
      `⚠️ Educational analysis only - not investment advice.`,
      `Generated by Stock Research Agent`,
    ];
    return lines.filter(l => l !== '').join('\n');
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = generateText();
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const dirColor: Record<string, { bg: string; text: string; border: string }> = {
    bullish: { bg: 'rgba(16, 185, 129, 0.1)', text: '#10b981', border: 'rgba(16, 185, 129, 0.3)' },
    bearish: { bg: 'rgba(239, 68, 68, 0.1)', text: '#ef4444', border: 'rgba(239, 68, 68, 0.3)' },
    neutral: { bg: 'rgba(245, 158, 11, 0.1)', text: '#f59e0b', border: 'rgba(245, 158, 11, 0.3)' },
    BUY: { bg: 'rgba(16, 185, 129, 0.1)', text: '#10b981', border: 'rgba(16, 185, 129, 0.3)' },
    SELL: { bg: 'rgba(239, 68, 68, 0.1)', text: '#ef4444', border: 'rgba(239, 68, 68, 0.3)' },
    HOLD: { bg: 'rgba(245, 158, 11, 0.1)', text: '#f59e0b', border: 'rgba(245, 158, 11, 0.3)' },
  };
  const colors = dirColor[direction] || dirColor['neutral'];

  return (
    <>
      <button
        onClick={() => setShowCard(!showCard)}
        className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium transition-all"
        style={{ background: 'var(--bg-badge)', color: 'var(--text-muted)' }}
      >
        <Share2 className="w-3.5 h-3.5" /> Share
      </button>

      {showCard && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(0,0,0,0.6)' }}>
          <div className="w-full max-w-md animate-scaleIn" onClick={e => e.stopPropagation()}>
            {/* Card Preview */}
            <div
              id="share-card"
              className="rounded-2xl p-6"
              style={{ background: 'var(--bg-card)', border: `2px solid ${colors.border}` }}
            >
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>{symbol}</h3>
                  <p className="text-xs" style={{ color: 'var(--text-dimmed)' }}>Stock Research Agent Analysis</p>
                </div>
                <div
                  className="px-3 py-1.5 rounded-xl text-sm font-semibold"
                  style={{ background: colors.bg, color: colors.text, border: `1px solid ${colors.border}` }}
                >
                  {emoji} {label}
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3 mb-4">
                <div className="text-center rounded-lg p-2" style={{ background: 'var(--bg-input)' }}>
                  <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Technical</p>
                  <p className="text-lg font-bold" style={{ color: 'var(--accent)' }}>{technicalScore}</p>
                </div>
                <div className="text-center rounded-lg p-2" style={{ background: 'var(--bg-input)' }}>
                  <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Fundamental</p>
                  <p className="text-lg font-bold" style={{ color: 'var(--accent)' }}>{fundamentalScore}</p>
                </div>
                <div className="text-center rounded-lg p-2" style={{ background: 'var(--bg-input)' }}>
                  <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Sentiment</p>
                  <p className="text-lg font-bold" style={{ color: 'var(--accent)' }}>{sentimentScore}</p>
                </div>
              </div>

              <div className="flex items-center justify-between mb-3 px-1">
                <div>
                  <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Price</p>
                  <p className="text-lg font-bold" style={{ color: 'var(--text-primary)' }}>${price.toFixed(2)}</p>
                </div>
                {targetPrice && (
                  <div className="text-right">
                    <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Est. Fair Value</p>
                    <p className="text-lg font-bold" style={{ color: colors.text }}>${targetPrice.toFixed(2)}</p>
                  </div>
                )}
                <div className="text-right">
                  <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Confidence</p>
                  <p className="text-lg font-bold" style={{ color: 'var(--text-primary)' }}>{(confidence * 100).toFixed(0)}%</p>
                </div>
              </div>

              <p className="text-xs line-clamp-3 mb-3" style={{ color: 'var(--text-secondary)' }}>{summary}</p>

              <p className="text-xs text-center" style={{ color: 'var(--text-dimmed)' }}>
                Educational analysis only - not investment advice
              </p>
            </div>

            {/* Actions */}
            <div className="flex gap-2 mt-3 justify-center">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-medium"
                style={{ background: 'var(--accent)', color: '#ffffff' }}
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy as Text'}
              </button>
              <button
                onClick={() => setShowCard(false)}
                className="px-4 py-2 rounded-xl text-sm font-medium"
                style={{ background: 'var(--bg-badge)', color: 'var(--text-secondary)' }}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
