'use client';

import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <main className="min-h-screen" style={{ background: 'var(--bg-page)', color: 'var(--text-primary)' }}>
      <div className="container mx-auto px-4 py-8 max-w-3xl">
        <Link href="/" className="inline-flex items-center gap-2 mb-8 text-sm" style={{ color: 'var(--accent)' }}>
          <ArrowLeft className="w-4 h-4" /> Back to Analysis
        </Link>

        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <p className="text-sm mb-8" style={{ color: 'var(--text-muted)' }}>Last updated: February 2026</p>

        <div className="space-y-8 text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
          <section>
            <h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>1. Educational Purpose Only</h2>
            <p>
              Stock Research Agent (&quot;the Tool&quot;) is an <strong>educational and informational tool only</strong>.
              It uses artificial intelligence and publicly available data to generate stock analysis for learning purposes.
              The Tool is designed to help users understand how different analytical frameworks (technical analysis,
              fundamental analysis, sentiment analysis, and risk assessment) work together.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>2. Not Investment Advice</h2>
            <p>
              <strong>Nothing on this platform constitutes investment advice, financial advice, trading advice,
              or any other form of professional advice.</strong> The analysis, signals, scores, directions, and any
              other output generated by this Tool should NOT be construed as a recommendation to buy, sell, or hold
              any security or financial instrument.
            </p>
            <p className="mt-2">
              The terms &quot;bullish signals,&quot; &quot;bearish signals,&quot; and &quot;mixed signals&quot; describe what data indicators suggest
              and are NOT instructions or recommendations to take any action.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>3. No Personalized Recommendations</h2>
            <p>
              The Tool does not consider your personal financial situation, investment objectives, risk tolerance,
              or any other individual factors. Any output from this Tool is generic and not tailored to any
              individual user. You should always consult with a qualified, licensed financial advisor who can
              provide personalized advice based on your specific circumstances.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>4. No Warranties</h2>
            <p>
              The Tool is provided &quot;as is&quot; and &quot;as available&quot; without any warranties of any kind, either express
              or implied. We do not guarantee the accuracy, completeness, timeliness, or reliability of any
              analysis, data, or information provided by the Tool. AI-generated content may contain errors,
              inaccuracies, or outdated information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>5. Limitation of Liability</h2>
            <p>
              In no event shall Stock Research Agent, its creators, contributors, or affiliates be liable for
              any direct, indirect, incidental, special, consequential, or punitive damages arising out of or
              relating to your use of or inability to use the Tool, including but not limited to any losses
              resulting from investment decisions made based on the Tool&apos;s output.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>6. Assumption of Risk</h2>
            <p>
              By using this Tool, you acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>All investments involve risk, including possible loss of principal</li>
              <li>Past performance does not guarantee future results</li>
              <li>You are solely responsible for your own investment decisions</li>
              <li>You will not rely on this Tool as your sole basis for any investment decision</li>
              <li>AI-generated analysis may be inaccurate or incomplete</li>
              <li>Market conditions can change rapidly and unpredictably</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>7. Third-Party Data</h2>
            <p>
              The Tool incorporates data from third-party sources including but not limited to financial data
              providers, news APIs, and analyst rating aggregators. We do not control, verify, or guarantee
              the accuracy of third-party data. Wall Street analyst ratings displayed are the opinions of
              those analysts and do not represent our views or recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>8. Contact</h2>
            <p>
              If you have questions about these Terms, please open an issue on our GitHub repository.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 text-center" style={{ borderTop: '1px solid var(--border-divider)' }}>
          <Link href="/" className="text-sm underline" style={{ color: 'var(--accent)' }}>
            Back to Stock Research Agent
          </Link>
        </div>
      </div>
    </main>
  );
}
